; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; --- CHIP CONFIGURATION (N16R8) ---
board_build.arduino.memory_type = qio_opi 
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

; Serial Monitor
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; --- LIBRARIES ---
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43 ; Display Driver
    lvgl/lvgl @ ^8.3.11       ; Graphic Interface

; --- HARDWARE CONFIGURATION ---
build_flags =
    ; LVGL CONFIGURATION
    -D LV_CONF_SKIP
    -D LV_CONF_INCLUDE_SIMPLE
    -D LV_CONF_SUPPRESS_DEFINE_CHECK
    -D LV_COLOR_DEPTH=16
    -D LV_TICK_CUSTOM=1
    ; DISPLAY CONFIGURATION
    -D USER_SETUP_LOADED=1
    -D ST7735_DRIVER=1
    -D ST7735_REDTAB=1
    -D TFT_WIDTH=128
    -D TFT_HEIGHT=128
    -D TFT_RGB_ORDER=TFT_RGB
    -D TFT_INVERSION_ON
    ; DISPLAY GPIO
    -D TFT_MISO=-1
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=6
    -D TFT_RST=14
    -D TFT_BL=38
    -D TFT_BACKLIGHT_ON=HIGH
    -D SPI_FREQUENCY=27000000 ; 27 MHz
